services:
  robot_hw:
    profiles: ["hw"]
    build:
      context: .
      dockerfile: Dockerfile
      target: hw
    container_name: scara_robot_hw
    network_mode: host
    privileged: true
    environment:
      SERIAL_PORT: /dev/ttyUSB0
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped

  robot_sim:
    profiles: ["sim"]
    build:
      context: .
      dockerfile: Dockerfile
      target: sim
    container_name: scara_robot_sim
    network_mode: host
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      CHOKIDAR_USEPOLLING: true
    volumes:
      # backend code (hot reload)
      - ./backend/main.py:/app/backend/main.py
      - ./presets_data:/app/backend

      # ros packages (active dev)
      - ./ros2_ws/src:/app/ros2_ws/src

      # frontend source (если хочешь dev mode)
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

      # X11 (GUI Gazebo)
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped
