controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController

scara_controller:
  ros__parameters:
    joints:
      - hand1_joint
      - hand2_joint
      - hand3_joint
      
    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity

    # Усиленные настройки PID для Gazebo
    gains:
      hand1_joint: {p: 10000.0, i: 0.0, d: 500.0}
      hand2_joint: {p: 10000.0, i: 0.0, d: 500.0}
      hand3_joint: {p: 5000.0, i: 0.0, d: 100.0}
