# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  hand1_joint:
    has_velocity_limits: true
    max_velocity: 2.0  # Или ваше значение из URDF
    has_acceleration_limits: true  # <--- БЫЛО FALSE
    max_acceleration: 2.0          # <--- ДОБАВЬТЕ ЭТО (рад/сек^2)
    joint_limit_margins: 0.01
  hand2_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true  # <--- БЫЛО FALSE
    max_acceleration: 2.0          # <--- ДОБАВЬТЕ ЭТО
    joint_limit_margins: 0.01
  hand3_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true  # <--- БЫЛО FALSE
    max_acceleration: 1.0          # <--- ДОБАВЬТЕ ЭТО (м/сек^2)
    joint_limit_margins: 0.01
