# Уровень 1: Имя ноды (move_group)
move_group:
  # Уровень 2: Ключевое слово (ОБЯЗАТЕЛЬНО для ROS 2 params-file)
  ros__parameters:
    # Уровень 3: Сами параметры
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - scara_controller

      scara_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - hand1_joint
          - hand2_joint
          - hand3_joint
